const PUZZLES = [
  {
    id: 1,
    title: "Murder at Blackwood Manor",
    difficulty: "Easy",
    emoji: "🏚️",
    story:
      "Lord Pemberton has been found dead in the Library of Blackwood Manor. Four guests were present that evening. The killer was alone with him in the Library. Use logic to place each suspect — one per row, one per column — and deduce who committed the murder.",
    gridSize: 4,
    rooms: [
      { name: "Library",    cells: [[0,0],[0,1],[1,0],[1,1]], color: "#7c3f1a", label: "Library"    },
      { name: "Study",      cells: [[0,2],[0,3],[1,2],[1,3]], color: "#1a5c3a", label: "Study"      },
      { name: "Dining Hall",cells: [[2,0],[2,1],[3,0],[3,1]], color: "#1a3a7c", label: "Dining Hall" },
      { name: "Ballroom",   cells: [[2,2],[2,3],[3,2],[3,3]], color: "#5c1a7c", label: "Ballroom"   },
    ],
    victim: {
      name: "Lord Pemberton",
      position: [1, 1],
      emoji: "💀",
    },
    suspects: [
      { id: "alice", name: "Alice Hartley",  emoji: "👩",       color: "#e74c3c" },
      { id: "bruno", name: "Bruno Sinclair", emoji: "🧔",       color: "#e67e22" },
      { id: "clara", name: "Clara Voss",     emoji: "👩‍🦳", color: "#27ae60" },
      { id: "diego", name: "Diego Reyes",    emoji: "🧑",       color: "#2980b9" },
    ],
    solution: {
      alice: [0, 2],
      bruno: [1, 0],
      clara: [2, 3],
      diego: [3, 1],
    },
    murderer: "bruno",
    clues: [
      { text: "Alice was seen in the Study all evening.", highlight: { rows: [0,1], cols: [2,3] } },
      { text: "Bruno never left the west wing (columns 1–2).", highlight: { rows: null, cols: [0,1] } },
      { text: "Clara spent the entire evening in the Ballroom.", highlight: { rows: [2,3], cols: [2,3] } },
      { text: "Diego was only seen on the ground floor (rows 3–4).", highlight: { rows: [2,3], cols: null } },
      { text: "Bruno was in the same row as Lord Pemberton.", highlight: { rows: [1], cols: null } },
      { text: "Clara arrived before Diego — she is in a higher row.", highlight: null },
      { text: "Alice's column position is to the left of Clara's.", highlight: null },
    ],
  },

  {
    id: 2,
    title: "Death at the Grand Hotel",
    difficulty: "Medium",
    emoji: "🏨",
    story:
      "The Hotel Manager has been found dead in the Hotel Lobby of the Grand Bellmont. Five guests were present that night. The killer was alone with him in the Lobby. One suspect per row, one per column — can you identify the murderer?",
    gridSize: 5,
    rooms: [
      { name: "Hotel Lobby", cells: [[0,0],[0,1],[1,0],[1,1]],
        color: "#7c2d12", label: "Lobby" },
      { name: "Restaurant",  cells: [[0,2],[0,3],[0,4],[1,2],[1,3],[1,4]],
        color: "#14532d", label: "Restaurant" },
      { name: "Garden",      cells: [[2,0],[2,1],[2,2],[2,3],[2,4]],
        color: "#166534", label: "Garden" },
      { name: "Cellar",      cells: [[3,0],[3,1],[3,2],[4,0],[4,1],[4,2]],
        color: "#1e3a5f", label: "Cellar" },
      { name: "Pool",        cells: [[3,3],[3,4],[4,3],[4,4]],
        color: "#0e4f6e", label: "Pool" },
    ],
    victim: {
      name: "The Hotel Manager",
      position: [0, 0],
      emoji: "💀",
    },
    suspects: [
      { id: "elena",    name: "Elena Vance",    emoji: "👩‍🦰", color: "#c0392b" },
      { id: "felix",    name: "Felix Moreau",   emoji: "🧑‍💼", color: "#d35400" },
      { id: "gabrielle",name: "Gabrielle Tan",  emoji: "👩",        color: "#27ae60" },
      { id: "hector",   name: "Hector Cruz",    emoji: "👨‍🦲", color: "#2471a3" },
      { id: "isabella", name: "Isabella Romanov",emoji: "👸",       color: "#8e44ad" },
    ],
    solution: {
      elena:    [0, 3],
      felix:    [1, 0],
      gabrielle:[2, 4],
      hector:   [3, 2],
      isabella: [4, 1],
    },
    murderer: "felix",
    clues: [
      { text: "Elena was dining in the Restaurant all evening.", highlight: { rows: [0,1], cols: [2,3,4] } },
      { text: "Felix was last seen in the Hotel Lobby.", highlight: { rows: [0,1], cols: [0,1] } },
      { text: "Gabrielle was strolling in the Garden.", highlight: { rows: [2], cols: null } },
      { text: "Hector was hiding in the Cellar.", highlight: { rows: [3,4], cols: [0,1,2] } },
      { text: "Isabella was also in the Cellar, deeper underground than Hector.", highlight: { rows: [3,4], cols: [0,1,2] } },
      { text: "Felix was directly below the victim — same column.", highlight: { rows: [1], cols: [0] } },
      { text: "Hector was in the rightmost column of the Cellar.", highlight: { rows: [3,4], cols: [2] } },
      { text: "Isabella was exactly one column to the left of Hector.", highlight: null },
      { text: "Elena sat at the center table (column 4) of the Restaurant.", highlight: { rows: [0], cols: [3] } },
    ],
  },

  {
    id: 3,
    title: "The Opera House Killing",
    difficulty: "Hard",
    emoji: "🎭",
    story:
      "The Conductor of the Royal Philharmonic has been found dead on the Stage of the Grand Opera House. Five suspects were present during the performance. The murderer was alone with the victim on the Stage. Solve this challenging puzzle — one suspect per row and column.",
    gridSize: 5,
    rooms: [
      { name: "Backstage", cells: [[0,0],[0,1],[1,0],[1,1]],
        color: "#422006", label: "Backstage" },
      { name: "Lobby",     cells: [[0,2],[0,3],[0,4],[1,2],[1,3],[1,4]],
        color: "#3d1a78", label: "Lobby" },
      { name: "Stage",     cells: [[2,0],[2,1],[2,2],[2,3],[3,0],[3,1],[3,2],[3,3]],
        color: "#7a1c2e", label: "Stage" },
      { name: "Orchestra", cells: [[2,4],[3,4],[4,4]],
        color: "#0f3460", label: "Orchestra" },
      { name: "Audience",  cells: [[4,0],[4,1],[4,2],[4,3]],
        color: "#1a3a2a", label: "Audience" },
    ],
    victim: {
      name: "The Conductor",
      position: [2, 2],
      emoji: "💀",
    },
    suspects: [
      { id: "amelia",  name: "Amelia Stone",   emoji: "🎻",        color: "#e74c3c" },
      { id: "baron",   name: "Baron Von Holt",  emoji: "🧐",        color: "#f39c12" },
      { id: "cecilia", name: "Cecilia Grimm",   emoji: "🎭",        color: "#8e44ad" },
      { id: "damian",  name: "Damian Blacke",   emoji: "🎸",        color: "#1abc9c" },
      { id: "evelyn",  name: "Evelyn Marsh",    emoji: "👩‍🎤", color: "#3498db" },
    ],
    solution: {
      amelia:  [0, 1],
      baron:   [1, 3],
      cecilia: [2, 0],
      damian:  [3, 4],
      evelyn:  [4, 2],
    },
    murderer: "cecilia",
    clues: [
      { text: "Amelia was in the Backstage area.", highlight: { rows: [0,1], cols: [0,1] } },
      { text: "Baron was in the Lobby.", highlight: { rows: [0,1], cols: [2,3,4] } },
      { text: "Damian was in the Orchestra Pit for the entire performance.", highlight: { rows: null, cols: [4] } },
      { text: "Evelyn was seated in the Audience.", highlight: { rows: [4], cols: [0,1,2,3] } },
      { text: "Amelia entered through the stage door — column 2.", highlight: { rows: [0,1], cols: [1] } },
      { text: "Baron had a seat in column 4 of the Lobby.", highlight: { rows: [0,1], cols: [3] } },
      { text: "Amelia arrived before Baron — she is in a higher row.", highlight: null },
      { text: "Cecilia was hiding in the leftmost position of the Stage.", highlight: { rows: [2,3], cols: [0] } },
      { text: "Damian arrived later than Cecilia — he is in a lower row.", highlight: null },
    ],
  },
];
