const PUZZLES = [
  {
    id: 1,
    title: "Murder at Blackwood Manor",
    difficulty: "Easy",
    emoji: "🏚️",
    story:
      "Lord Pemberton has been found dead in the Library of Blackwood Manor. Four guests were present that evening. The killer was alone with him in the Library. Use logic to place each suspect — one per row, one per column — and deduce who committed the murder.",
    gridSize: 4,
    rooms: [
      { name: "Library",    cells: [[0,0],[0,1],[1,0],[1,1]], color: "#e8b870", textColor: "#5c3a00" },
      { name: "Study",      cells: [[0,2],[0,3],[1,2],[1,3]], color: "#90c890", textColor: "#1a4a1a" },
      { name: "Dining Hall",cells: [[2,0],[2,1],[3,0],[3,1]], color: "#90b8e0", textColor: "#1a2f5a" },
      { name: "Ballroom",   cells: [[2,2],[2,3],[3,2],[3,3]], color: "#d8a8d8", textColor: "#4a1a5a" },
    ],
    victim: {
      name: "Lord Pemberton",
      position: [1, 1],
      emoji: "💀",
    },
    suspects: [
      { id: "alice", name: "Alice Hartley",  emoji: "👩",  color: "#c0392b" },
      { id: "bruno", name: "Bruno Sinclair", emoji: "🧔",  color: "#d07010" },
      { id: "clara", name: "Clara Voss",     emoji: "👩‍🦳", color: "#2e8b57" },
      { id: "diego", name: "Diego Reyes",    emoji: "🧑",  color: "#2471a3" },
    ],
    solution: {
      alice: [0, 2],
      bruno: [1, 0],
      clara: [2, 3],
      diego: [3, 1],
    },
    murderer: "bruno",
    clues: [
      { text: "Alice was seen in the Study all evening.", highlight: { rows: [0,1], cols: [2,3] } },
      { text: "Bruno never left the west wing (left half of the manor).", highlight: { rows: null, cols: [0,1] } },
      { text: "Clara spent the entire evening in the Ballroom.", highlight: { rows: [2,3], cols: [2,3] } },
      { text: "Diego was only seen on the ground floor (rows 3–4).", highlight: { rows: [2,3], cols: null } },
      { text: "Bruno was in the same row as Lord Pemberton.", highlight: { rows: [1], cols: null } },
      { text: "Clara arrived before Diego — she is in a higher row.", highlight: null },
      { text: "Alice's column position is to the left of Clara's.", highlight: null },
    ],
  },

  {
    id: 2,
    title: "Death at the Grand Hotel",
    difficulty: "Medium",
    emoji: "🏨",
    story:
      "The Hotel Manager has been found dead in the Hotel Lobby of the Grand Bellmont. Five guests were present that night. The killer was alone with him in the Lobby. One suspect per row, one per column — can you identify the murderer?",
    gridSize: 5,
    rooms: [
      { name: "Lobby",      cells: [[0,0],[0,1],[1,0],[1,1]],
        color: "#f0c878", textColor: "#5c3800" },
      { name: "Restaurant", cells: [[0,2],[0,3],[0,4],[1,2],[1,3],[1,4]],
        color: "#98d898", textColor: "#1a4a1a" },
      { name: "Garden",     cells: [[2,0],[2,1],[2,2],[2,3],[2,4]],
        color: "#70c870", textColor: "#0f3a0f" },
      { name: "Cellar",     cells: [[3,0],[3,1],[3,2],[4,0],[4,1],[4,2]],
        color: "#a8a8e0", textColor: "#1a1a5a" },
      { name: "Pool",       cells: [[3,3],[3,4],[4,3],[4,4]],
        color: "#78c8f0", textColor: "#0a2a4a" },
    ],
    victim: {
      name: "Hotel Manager",
      position: [0, 0],
      emoji: "💀",
    },
    suspects: [
      { id: "elena",     name: "Elena Vance",     emoji: "👩‍🦰", color: "#c0392b" },
      { id: "felix",     name: "Felix Moreau",    emoji: "🧑‍💼", color: "#d07010" },
      { id: "gabrielle", name: "Gabrielle Tan",   emoji: "👩",   color: "#27ae60" },
      { id: "hector",    name: "Hector Cruz",     emoji: "👨‍🦲", color: "#2471a3" },
      { id: "isabella",  name: "Isabella Romanov",emoji: "👸",   color: "#8e44ad" },
    ],
    solution: {
      elena:     [0, 3],
      felix:     [1, 0],
      gabrielle: [2, 4],
      hector:    [3, 2],
      isabella:  [4, 1],
    },
    murderer: "felix",
    clues: [
      { text: "Elena was dining in the Restaurant all evening.", highlight: { rows: [0,1], cols: [2,3,4] } },
      { text: "Felix was last seen in the Hotel Lobby.", highlight: { rows: [0,1], cols: [0,1] } },
      { text: "Gabrielle was strolling in the Garden.", highlight: { rows: [2], cols: null } },
      { text: "Hector was hiding in the Cellar.", highlight: { rows: [3,4], cols: [0,1,2] } },
      { text: "Isabella was also in the Cellar, deeper underground than Hector.", highlight: { rows: [3,4], cols: [0,1,2] } },
      { text: "Felix was directly below the victim — they share the same column.", highlight: { rows: [1], cols: [0] } },
      { text: "Hector was in the rightmost column of the Cellar.", highlight: { rows: [3,4], cols: [2] } },
      { text: "Isabella was exactly one column to the left of Hector.", highlight: null },
      { text: "Elena sat at the 4th seat from the left in the Restaurant.", highlight: { rows: [0], cols: [3] } },
    ],
  },

  {
    id: 3,
    title: "The Opera House Killing",
    difficulty: "Hard",
    emoji: "🎭",
    story:
      "The Conductor of the Royal Philharmonic has been found dead on the Stage of the Grand Opera House. Five suspects were present during the performance. The murderer was alone with the victim on the Stage. Solve this challenging puzzle — one suspect per row and column.",
    gridSize: 5,
    rooms: [
      { name: "Backstage", cells: [[0,0],[0,1],[1,0],[1,1]],
        color: "#e0c090", textColor: "#4a2a00" },
      { name: "Lobby",     cells: [[0,2],[0,3],[0,4],[1,2],[1,3],[1,4]],
        color: "#c0a8e8", textColor: "#280a5a" },
      { name: "Stage",     cells: [[2,0],[2,1],[2,2],[2,3],[3,0],[3,1],[3,2],[3,3]],
        color: "#f09898", textColor: "#5a0a0a" },
      { name: "Orchestra", cells: [[2,4],[3,4],[4,4]],
        color: "#90b8e8", textColor: "#0a2a5a" },
      { name: "Audience",  cells: [[4,0],[4,1],[4,2],[4,3]],
        color: "#a8d8a8", textColor: "#0a3a0a" },
    ],
    victim: {
      name: "The Conductor",
      position: [2, 2],
      emoji: "💀",
    },
    suspects: [
      { id: "amelia",  name: "Amelia Stone",  emoji: "🎻",  color: "#c0392b" },
      { id: "baron",   name: "Baron Von Holt", emoji: "🧐",  color: "#d07010" },
      { id: "cecilia", name: "Cecilia Grimm", emoji: "🎭",  color: "#8e44ad" },
      { id: "damian",  name: "Damian Blacke", emoji: "🎸",  color: "#1abc9c" },
      { id: "evelyn",  name: "Evelyn Marsh",  emoji: "🎤",  color: "#2471a3" },
    ],
    solution: {
      amelia:  [0, 1],
      baron:   [1, 3],
      cecilia: [2, 0],
      damian:  [3, 4],
      evelyn:  [4, 2],
    },
    murderer: "cecilia",
    clues: [
      { text: "Amelia was in the Backstage area.", highlight: { rows: [0,1], cols: [0,1] } },
      { text: "Baron was in the Lobby.", highlight: { rows: [0,1], cols: [2,3,4] } },
      { text: "Damian was in the Orchestra Pit for the entire performance.", highlight: { rows: null, cols: [4] } },
      { text: "Evelyn was seated in the Audience.", highlight: { rows: [4], cols: [0,1,2,3] } },
      { text: "Amelia entered through the stage door at column 2.", highlight: { rows: [0,1], cols: [1] } },
      { text: "Baron had a seat in column 4 of the Lobby.", highlight: { rows: [0,1], cols: [3] } },
      { text: "Amelia arrived before Baron — she is in a higher row.", highlight: null },
      { text: "Cecilia was hiding in the leftmost position of the Stage.", highlight: { rows: [2,3], cols: [0] } },
      { text: "Damian arrived later than Cecilia — he is in a lower row.", highlight: null },
    ],
  },

  // ── Puzzle 4 ───────────────────────────────────────────────────────
  {
    id: 4,
    title: "The Museum Heist Gone Wrong",
    difficulty: "Medium",
    emoji: "🏛️",
    story:
      "The Museum Curator has been found dead in the Restoration Lab during last night's gala. Five suspects were present at the event. The killer was alone with her in the Restoration Lab. Place each suspect — one per row, one per column — and identify the murderer.",
    gridSize: 5,
    rooms: [
      { name: "Grand Hall",       cells: [[0,0],[0,1],[1,0],[1,1]],                         color: "#f0c878", textColor: "#5c3800" },
      { name: "Vault",            cells: [[0,2],[0,3],[0,4],[1,2],[1,3],[1,4]],              color: "#a8c8e8", textColor: "#0a2a5a" },
      { name: "Restoration Lab",  cells: [[2,0],[2,1],[2,2]],                               color: "#f0a888", textColor: "#5a1a00" },
      { name: "Archives",         cells: [[2,3],[2,4],[3,2],[3,3],[3,4],[4,2],[4,3],[4,4]], color: "#b8d8a0", textColor: "#1a4a0a" },
      { name: "Sculpture Garden", cells: [[3,0],[3,1],[4,0],[4,1]],                         color: "#d8c8f0", textColor: "#2a0a5a" },
    ],
    victim: { name: "The Curator", position: [2, 1], emoji: "💀" },
    suspects: [
      { id: "nadia",  name: "Nadia Okonkwo",  emoji: "👩‍💼", color: "#c0392b" },
      { id: "jasper", name: "Jasper Wren",    emoji: "🧑‍🎨", color: "#d07010" },
      { id: "tobias", name: "Tobias Fenn",    emoji: "🕵️",  color: "#8e44ad" },
      { id: "serena", name: "Serena Toth",    emoji: "👩",   color: "#27ae60" },
      { id: "prof",   name: "Prof. Hargrove", emoji: "🧓",   color: "#2471a3" },
    ],
    solution: {
      nadia:  [0, 0],
      jasper: [1, 4],
      tobias: [2, 2],
      serena: [3, 3],
      prof:   [4, 1],
    },
    murderer: "tobias",
    clues: [
      { text: "Tobias was seen pacing the Restoration Lab throughout the evening.", highlight: { rows: [2], cols: [0,1,2] } },
      { text: "Prof. Hargrove never left the Sculpture Garden.", highlight: { rows: [3,4], cols: [0,1] } },
      { text: "Jasper spent the night examining pieces in the Vault.", highlight: { rows: [0,1], cols: [2,3,4] } },
      { text: "Nadia was chatting with guests in the Grand Hall.", highlight: { rows: [0,1], cols: [0,1] } },
      { text: "Serena worked late cataloguing in the Archives.", highlight: { rows: [2,3,4], cols: [2,3,4] } },
      { text: "Nadia signed the guestbook first — she was in the front row.", highlight: { rows: [0], cols: null } },
      { text: "Nadia stood at the leftmost column of the Grand Hall.", highlight: { rows: null, cols: [0] } },
      { text: "Prof. Hargrove occupied the very back row of the museum.", highlight: { rows: [4], cols: null } },
      { text: "Serena's cataloguing desk was in column 4.", highlight: { rows: null, cols: [3] } },
    ],
  },

  // ── Puzzle 5 ───────────────────────────────────────────────────────
  {
    id: 5,
    title: "Murder in the Vineyard",
    difficulty: "Expert",
    emoji: "🍇",
    story:
      "The renowned Vintner has been found dead in the Fermentation Cellar during the harvest banquet. Six suspects attended the evening. The killer was alone with him in the Cellar. One suspect per row, one per column — this is the hardest case yet.",
    gridSize: 6,
    rooms: [
      { name: "Tasting Room",        cells: [[0,0],[0,1],[0,2],[1,0],[1,1],[1,2]],           color: "#f0c878", textColor: "#5c3800" },
      { name: "Grand Terrace",       cells: [[0,3],[0,4],[0,5],[1,3],[1,4],[1,5]],           color: "#90c890", textColor: "#1a4a1a" },
      { name: "Barrel Hall",         cells: [[2,0],[2,1],[2,2],[2,3],[3,0],[3,1],[3,2],[3,3]],color: "#c8a870", textColor: "#4a2800" },
      { name: "Press House",         cells: [[2,4],[2,5],[3,4],[3,5]],                       color: "#d0a8d0", textColor: "#3a0a4a" },
      { name: "Fermentation Cellar", cells: [[4,0],[4,1],[4,2],[5,0],[5,1],[5,2]],           color: "#a8b8e0", textColor: "#0a1a5a" },
      { name: "Vine Cottage",        cells: [[4,3],[4,4],[4,5],[5,3],[5,4],[5,5]],           color: "#b8d8a0", textColor: "#1a4a0a" },
    ],
    victim: { name: "The Vintner", position: [4, 1], emoji: "💀" },
    suspects: [
      { id: "colette", name: "Colette Duval",  emoji: "🍷",       color: "#c0392b" },
      { id: "marcus",  name: "Marcus Vane",    emoji: "🧑‍🌾", color: "#d07010" },
      { id: "phoebe",  name: "Phoebe Ashford", emoji: "👩‍🔬", color: "#27ae60" },
      { id: "renato",  name: "Renato Greco",   emoji: "👨",        color: "#2471a3" },
      { id: "theo",    name: "Theo Harker",    emoji: "🕵️",       color: "#8e44ad" },
      { id: "sylvia",  name: "Sylvia Crane",   emoji: "👩‍🦱", color: "#c05818" },
    ],
    solution: {
      colette: [0, 2],
      marcus:  [1, 5],
      phoebe:  [2, 4],
      renato:  [3, 1],
      theo:    [4, 3],
      sylvia:  [5, 0],
    },
    murderer: "sylvia",
    clues: [
      { text: "Colette spent the evening in the Tasting Room.", highlight: { rows: [0,1], cols: [0,1,2] } },
      { text: "Marcus was sipping wine on the Grand Terrace.", highlight: { rows: [0,1], cols: [3,4,5] } },
      { text: "Phoebe was inspecting machinery in the Press House.", highlight: { rows: [2,3], cols: [4,5] } },
      { text: "Renato was working barrels in the Barrel Hall.", highlight: { rows: [2,3], cols: [0,1,2,3] } },
      { text: "Sylvia was seen entering the Fermentation Cellar early in the evening.", highlight: { rows: [4,5], cols: [0,1,2] } },
      { text: "Theo was relaxing in the Vine Cottage.", highlight: { rows: [4,5], cols: [3,4,5] } },
      { text: "Colette was seated in the very first row of the evening.", highlight: { rows: [0], cols: null } },
      { text: "Marcus chose the last seat in his row — column 6.", highlight: { rows: null, cols: [5] } },
      { text: "Colette sat at the rightmost table of the Tasting Room.", highlight: { rows: [0,1], cols: [2] } },
      { text: "Renato was working the lower level of the Barrel Hall.", highlight: { rows: [3], cols: [0,1,2,3] } },
      { text: "Phoebe's station was in column 5 of the Press House.", highlight: { rows: null, cols: [4] } },
      { text: "Renato's barrel cask was at the 2nd column.", highlight: { rows: null, cols: [1] } },
      { text: "Theo settled in before Sylvia — he was in an earlier row than her.", highlight: null },
    ],
  },
];
